/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videoattributer.gui;

import ExcelReading.ReadWriteExcelFile;
import static ExcelReading.ReadWriteExcelFile.videos;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import videoattributer.metadata.writer;
import videoattributer.object.Video;
import videoattributer.object.VideoMetadata;
import videoattributer.table.renderers.ColorColumnRenderer;
import videoattributer.table.TableService;

/**
 *
 * @author Jesus Soto
 */
public class main extends javax.swing.JFrame {

    public static DefaultTableModel TableVideoModel;
    public static String videoDirectorySourcePath = "";
    String selectedTableItem = "";
    public static List<String> videosToEdit = new ArrayList<String>();
    
    public main() {
        initComponents();    
        build_InitializationTable();
        setIconImage(new ImageIcon(getClass().getResource("metadata.png")).getImage());
        jProgressBar2.setVisible(false);
        jLabel1.setVisible(false);
        jDialog1.setUndecorated(true);
        jDialog1.setAlwaysOnTop(true);        
        jDialog1.setLocation(520, 300);
        jDialog1.setSize(520, 80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        FileChooserWindow = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VideoTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comments = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentComments = new javax.swing.JTextPane();
        currentName = new javax.swing.JLabel();
        currentTitle = new javax.swing.JLabel();
        currentSubtitle = new javax.swing.JLabel();
        currentRating = new javax.swing.JLabel();
        currentTags = new javax.swing.JLabel();
        currentAuthor_url = new javax.swing.JLabel();
        currentPromotion_url = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newTitle = new javax.swing.JTextField();
        newSubtitles = new javax.swing.JTextField();
        newTags = new javax.swing.JTextField();
        newAuthor_URL = new javax.swing.JTextField();
        newPromotion_URL = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        newComments = new javax.swing.JTextArea();
        newRating = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FileChooserWindowLayout = new javax.swing.GroupLayout(FileChooserWindow.getContentPane());
        FileChooserWindow.getContentPane().setLayout(FileChooserWindowLayout);
        FileChooserWindowLayout.setHorizontalGroup(
            FileChooserWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FileChooserWindowLayout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        FileChooserWindowLayout.setVerticalGroup(
            FileChooserWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FileChooserWindowLayout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        jLabel18.setText("Editing videos, please wait . . .");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("jLabel1");

        jLabel16.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel16.setText("Made by: Aiotik, LLC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        VideoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(VideoTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Video Properties"));

        jLabel10.setText("Video Name:");

        jLabel11.setText("Author URL:");

        jLabel12.setText("TAGS:");

        jLabel13.setText("Title:");

        jLabel14.setText("Subtitle:");

        jLabel15.setText("Rating:");

        jLabel17.setText("Promotion URL:");

        comments.setText("Comments:");

        currentComments.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentComments.setText("No Comments");
        currentComments.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        currentComments.setEnabled(false);
        jScrollPane3.setViewportView(currentComments);

        currentName.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentName.setText("N/A");

        currentTitle.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentTitle.setText("N/A");

        currentSubtitle.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentSubtitle.setText("N/A");

        currentRating.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentRating.setText("N/A");

        currentTags.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentTags.setText("N/A");

        currentAuthor_url.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentAuthor_url.setText("N/A");

        currentPromotion_url.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        currentPromotion_url.setText("N/A");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentName)
                    .addComponent(currentTitle)
                    .addComponent(currentSubtitle)
                    .addComponent(currentRating))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(comments, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentTags)
                    .addComponent(currentAuthor_url)
                    .addComponent(currentPromotion_url)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(currentName)
                    .addComponent(currentTags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(currentTitle)
                    .addComponent(currentAuthor_url))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(currentSubtitle)
                    .addComponent(currentPromotion_url))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comments)
                        .addComponent(jLabel15)
                        .addComponent(currentRating))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("New Video Properties"));

        jLabel2.setText("Video Name:");

        jLabel3.setText("Title:");

        jLabel4.setText("Subtitle:");

        jLabel5.setText("Rating:");

        jLabel6.setText("TAGS:");

        jLabel7.setText("Comments:");

        jLabel8.setText("Author URL:");

        jLabel9.setText("Promotion URL:");

        newName.setText("N/A");
        newName.setEnabled(false);

        newTitle.setText("N/A");
        newTitle.setEnabled(false);

        newSubtitles.setText("N/A");
        newSubtitles.setEnabled(false);

        newTags.setText("N/A");
        newTags.setEnabled(false);

        newAuthor_URL.setText("N/A");
        newAuthor_URL.setEnabled(false);

        newPromotion_URL.setText("N/A");
        newPromotion_URL.setEnabled(false);

        newComments.setColumns(20);
        newComments.setRows(5);
        newComments.setText("N/A");
        newComments.setEnabled(false);
        jScrollPane2.setViewportView(newComments);

        newRating.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        newRating.setEnabled(false);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newSubtitles)
                        .addComponent(newName, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(newTags)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newAuthor_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newRating, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newPromotion_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSubtitles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(newRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(newAuthor_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(newPromotion_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jButton3.setText("Import Spreadsheet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Start Edition");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Import File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Execute Edition");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        chooseSpreadsheet();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void chooseSpreadsheet(){
        FileChooserWindow.setVisible(true); 
        FileChooserWindow.setResizable(false);
        FileChooserWindow.setSize(510, 350);
        FileChooserWindow.setLocation(500, 200);
        FileChooserWindow.setTitle("Choose a spreadsheet");
        jFileChooser1.setFileSelectionMode(0);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Spreadsheets (.xls, .xlsx)", "xls", "xlsx");
        jFileChooser1.setFileFilter(filter);
        VideoTable.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        jPanel3.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        jPanel4.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }       
    
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
              
        if(jFileChooser1.getFileSelectionMode() == 0){     
            jButton4.setEnabled(false);
            jMenuItem3.setEnabled(false);
            File spreadsheet = jFileChooser1.getSelectedFile();
            FileChooserWindow.dispose();

            // Gets the format of the file selected
            String fileAbsolutePath=spreadsheet.getName();
            spreadsheet.getAbsolutePath();
            String fileExtension = fileAbsolutePath.substring(fileAbsolutePath.lastIndexOf(".") + 1, fileAbsolutePath.length());                         

            try{
                ReadWriteExcelFile decoder = new ReadWriteExcelFile();

                if(fileExtension.equals("xls")){                           
                    decoder.readXLSFile(spreadsheet.toString());
                }else if(fileExtension.equals("xlsx")){            
                    decoder.readXLSXFile(spreadsheet.toString());
                }
            }catch(Exception e){
                System.err.println("Error getting files in main.java "+e);
                e.printStackTrace();
            }   
        }else{
            FileChooserWindow.dispose();
            videoDirectorySourcePath = jFileChooser1.getSelectedFile().toString();            
            
            //If all went successfully
            if(TableService.SetDefaultTableStyle()){
              //Fills the fields with the desired properties
               selectedTableItem = videos.get(0).getName();
               load_desiredProperties(videos.get(0).getName(), videos.get(0).getAuthor_url(), 
                                      videos.get(0).getComments(), videos.get(0).getPromotion_url(), 
                                      videos.get(0).getRating(), videos.get(0).getSubtitles(), 
                                      videos.get(0).getTags(), videos.get(0).getTitle());
            }                        
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    public void load_desiredProperties(String name, String authorUrl, String comments,
            String promotionUrl, String rating, String subtitles, String tags, String title){
               
        newName.setText(name);
        newAuthor_URL.setText(authorUrl);
        newComments.setText(comments);
        newPromotion_URL.setText(promotionUrl);
        Double v = Double.parseDouble(rating);         
        newRating.setValue(v * 1);
        newSubtitles.setText(subtitles);
        newTags.setText(tags);
        newTitle.setText(title);
    }
    
    public void load_currentProperties(String name, String authorUrl, String comments,
            String promotionUrl, String rating, String subtitles, String tags, String title){
        
        currentName.setText(name);
        currentAuthor_url.setText(authorUrl);
        currentComments.setText(comments);
        currentPromotion_url.setText(promotionUrl);
        currentRating.setText(rating.toString());
        currentSubtitle.setText(subtitles);
        currentTags.setText(tags);
        currentTitle.setText(title);
    }
    
    public static void showChooserForVideosRoute(){
        FileChooserWindow.setVisible(true); 
        FileChooserWindow.setResizable(false);
        FileChooserWindow.setSize(510, 350);
        FileChooserWindow.setLocation(500, 200);
        FileChooserWindow.setTitle("Choose a directory to look for the videos specified...");  
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Directories Only", "File Path...");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.setFileSelectionMode(DIRECTORIES_ONLY);
    }
    
    public void build_InitializationTable(){
          String[] titles = {"No spreadsheet imported yet."};       
          TableVideoModel=new DefaultTableModel(null, titles){
                @Override
                 public boolean isCellEditable(int row1, int column) {   
                     if(column == 2){
                         return true;
                     }
                     return false;
                 }
                 private static final long serialVersionUID = 1L;  
                @Override
                public Class<?> getColumnClass(int column) {  
                    switch (column) {  
                        case 0:
                            return String.class;
                        case 1:  
                            return String.class;
                        case 2:  
                            return Boolean.class;
                        case 3:  
                            return String.class; 
                        default:
                            return   String.class;
                    }  
                } 
           };
        try{  
            TableVideoModel.addRow(new Object[]{"               "
                    + "Please, import a spreadsheet with the video data."});            
         }catch(Exception e){
             System.err.println(e);
        }                 
        
        //Setting colors and size
        VideoTable.setRowHeight(150);
        VideoTable.setModel(TableVideoModel);
        VideoTable.setFont(new Font("Dialog", Font.ITALIC, 20));   
        VideoTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 20));
        
        VideoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VideoTableMouseClicked(evt);
            }

            private void VideoTableMouseClicked(MouseEvent evt) {
                loadInfoFromSelectedRow();       
            }
        });
        
        VideoTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VideoTableKeyPressed(evt);
            }
            
            public void VideoTableKeyPressed(KeyEvent evt){                
                if(evt.getKeyCode() == 38 || evt.getKeyCode() == 40){
                    loadInfoFromSelectedRow();
                }
            }
        });
        
        TableColumn tm = VideoTable.getColumnModel().getColumn(0);
        tm.setCellRenderer(new ColorColumnRenderer(new Color(191,191,191), new Color(0, 38, 77)));
    }
    
    public void loadInfoFromSelectedRow(){        
        String videoName = VideoTable.getValueAt(VideoTable.getSelectedRow(), 0).toString();
        selectedTableItem = videoName;

        for(Video video: videos){
            if(video.getName().equals(videoName)){                      
              load_desiredProperties(video.getName(), video.getAuthor_url(), 
                               video.getComments(), video.getPromotion_url(),
                               video.getRating(), video.getSubtitles(), 
                               video.getTags(), video.getTitle());                                                        
              
              if(video.getVideoMetadata()!=null){                  
                VideoMetadata metadata = video.getVideoMetadata();               
                load_currentProperties(metadata.getName(), metadata.getAuthor_url(), metadata.getComments(),
                                      metadata.getPromotion_url(), metadata.getRating(), metadata.getSubtitles(), 
                                      metadata.getTags(), metadata.getTitle());
              }
            }
        }   
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        chooseSpreadsheet();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(!videos.isEmpty()){
             setTextBoxAvailability(true);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setTextBoxAvailability(false);        
        if(!videos.isEmpty()){            
            for(Video video: videos){
                if(video.getName().equals(selectedTableItem)){
                    video.setAuthor_url(newAuthor_URL.getText());
                    video.setComments(newComments.getText());
                    video.setName(newName.getText());
                    video.setPromotion_url(newPromotion_URL.getText());
                    video.setRating(newRating.getValue().toString());
                    video.setSubtitles(newSubtitles.getText());
                    video.setTags(newTags.getText());
                    video.setTitle(newTitle.getText());
                    
                    VideoTable.setValueAt(newName.getText(), VideoTable.getSelectedRow(), 0);                    
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             
        jDialog1.setVisible(true);
        VideoTable.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        jPanel3.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        jPanel4.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        executeEdition();
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void executeEdition(){        
        for(int i=0; i<TableVideoModel.getRowCount(); i++){            
            if(VideoTable.getValueAt(i, 2).toString().equals("true")){                
                videosToEdit.add(VideoTable.getValueAt(i, 0).toString());
            }
        }                
        new writer().InsertNewMetadata();
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jPanel3.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        jPanel4.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        executeEdition();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    public void setTextBoxAvailability(boolean avialabilty){
        newName.setEnabled(avialabilty);
        newAuthor_URL.setEnabled(avialabilty);
        newComments.setEnabled(avialabilty);
        newPromotion_URL.setEnabled(avialabilty);
        newRating.setEnabled(avialabilty);
        newSubtitles.setEnabled(avialabilty);
        newTags.setEnabled(avialabilty);
        newTitle.setEnabled(avialabilty);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDialog FileChooserWindow;
    public static javax.swing.JTable VideoTable;
    private javax.swing.JLabel comments;
    private javax.swing.JLabel currentAuthor_url;
    private javax.swing.JTextPane currentComments;
    private javax.swing.JLabel currentName;
    private javax.swing.JLabel currentPromotion_url;
    private javax.swing.JLabel currentRating;
    private javax.swing.JLabel currentSubtitle;
    private javax.swing.JLabel currentTags;
    private javax.swing.JLabel currentTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JDialog jDialog1;
    public static javax.swing.JFileChooser jFileChooser1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField newAuthor_URL;
    private javax.swing.JTextArea newComments;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newPromotion_URL;
    private javax.swing.JSpinner newRating;
    private javax.swing.JTextField newSubtitles;
    private javax.swing.JTextField newTags;
    private javax.swing.JTextField newTitle;
    // End of variables declaration//GEN-END:variables
}
